apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: arf-ids-incremental-retrain
  namespace: argo
spec:
  schedule: "{{ .Values.argoWorkflows.retrain.schedule }}"
  concurrencyPolicy: Forbid

  workflowSpec:
    entrypoint: retrain

    templates:
      - name: retrain
        container:
          image: "{{ .Values.argoWorkflows.retrain.image }}"
          imagePullPolicy: Always
          command: ["python", "retrain_incremental.py"]

          env:
            - name: MLFLOW_TRACKING_URI
              value: "https://mlflow.qmuit.id.vn"
            - name: MODEL_NAME
              value: "ARF Baseline Model"
            - name: S3_BUCKET
              value: "qmuit-ids-training-data-store"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"

        resources:
          limits:
            cpu: "{{ .Values.argoWorkflows.retrain.resources.cpu }}"
            memory: "{{ .Values.argoWorkflows.retrain.resources.memory }}"
