# =====================================================================================
# IDS API
# =====================================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ids-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: {{ .Values.api.path }}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---

# =====================================================================================
# IDS MLFLOW (MLflow UI + API)
# =====================================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ids-mlflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: {{ .Values.mlflow.path }}
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow      # <<< sửa namespace để cùng Postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true

---

# =====================================================================================
# IDS MLFLOW POSTGRES (Bitnami PostgreSQL)
# =====================================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ids-mlflow-postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 16.0.1
    helm:
      releaseName: ids-mlflow-postgres
      values: |
        global:
          postgresql:
            auth:
              username: mlflow
              password: mlflow123
              database: mlflow

        primary:
          image:
            repository: docker.io/bitnami/postgresql
            tag: 15.5.0-debian-11-r0     # <<< phiên bản ổn định, tương thích với chart
            pullPolicy: IfNotPresent

          persistence:
            enabled: true
            size: 10Gi
            storageClass: gp3

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow        # <<< chạy đúng namespace với MLflow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true

---

# =====================================================================================
# ARGO WORKFLOWS
# =====================================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ids-argo-workflows
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-workflows
    targetRevision: 0.45.28
    helm:
      releaseName: argo-workflows
      values: |
        server:
          enabled: true
          authMode: server
          insecure: true
          ingress:
            enabled: true
            ingressClassName: alb
            annotations:
              alb.ingress.kubernetes.io/scheme: internet-facing
              alb.ingress.kubernetes.io/target-type: ip
              alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
            hosts:
              - workflows.qmuit.id.vn
            paths:
              - path: /
                pathType: Prefix

        controller:
          workflowNamespaces:
            - default
            - argo

  destination:
    server: https://kubernetes.default.svc
    namespace: argo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true

---

# =====================================================================================
# STORAGECLASS
# =====================================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ids-storageclass
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: values/storageclass
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - ApplyOutOfSyncOnly=true
