apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ids-api
  namespace: argocd
spec:
  project: default

  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: {{ .Values.api.path }}

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ids-mlflow
  namespace: argocd
spec:
  project: default

  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: {{ .Values.mlflow.path }}

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ids-mlflow-postgres
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.5.2
    helm:
      releaseName: ids-mlflow-postgres
      values: |
        global:
          postgresql:
            auth:
              username: mlflow
              password: mlflow123
              database: mlflow
        primary:
          persistence:
            enabled: true
            size: 10Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true

