# =====================================================================================
# IDS API
# =====================================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ids-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: {{ .Values.api.path }}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /status
        - /metadata/annotations
        - /metadata/managedFields

---
# =====================================================================================
# IDS MLFLOW UI/API
# =====================================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ids-mlflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: {{ .Values.mlflow.path }}
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /status
        - /metadata/annotations
        - /metadata/managedFields

---
# =====================================================================================
# IDS MLFLOW POSTGRES
# =====================================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ids-mlflow-postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 16.0.1
    helm:
      releaseName: ids-mlflow-postgres
      values: |
        image:
          registry: docker.io
          repository: bitnami/postgresql
          tag: latest
          pullPolicy: IfNotPresent

        global:
          postgresql:
            auth:
              username: mlflow
              password: mlflow123
              database: mlflow

        primary:
          persistence:
            enabled: true
            size: 10Gi
            storageClass: gp3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /status
        - /metadata/annotations
        - /metadata/managedFields

---
# =====================================================================================
# IDS ARGO WORKFLOWS (FULL + FIXED)
# =====================================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ids-argo-workflows
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-workflows
    targetRevision: 0.45.28

    helm:
      releaseName: argo-workflows
      values: |
        # ========================================================
        # ARGO SERVER CONFIG
        # ========================================================
        server:
          enabled: true
          authMode: server
          insecure: true
          secure: false

          ingress:
            enabled: true
            ingressClassName: alb
            annotations:
              alb.ingress.kubernetes.io/scheme: internet-facing
              alb.ingress.kubernetes.io/target-type: ip
              alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
              alb.ingress.kubernetes.io/backend-protocol: HTTP
            hosts:
              - workflows.qmuit.id.vn
            paths:
              - /

        # ========================================================
        # WORKFLOW CONTROLLER CONFIG
        # ========================================================
        controller:
          workflowNamespaces:
            - default
            - argo

        # ========================================================
        # ARTIFACT REPOSITORY (S3)
        # ========================================================
        workflow:
          artifactRepository:
            s3:
              bucket: qmuit-training-data-store
              endpoint: s3.amazonaws.com
              region: us-east-1
              insecure: false
              accessKeySecret:
                name: argo-s3-secret
                key: accesskey
              secretKeySecret:
                name: argo-s3-secret
                key: secretkey

        # ========================================================
        # ENABLE WORKFLOW + NODE EVENTS
        # ========================================================
        config:
          workflowEvents:
            enabled: true
          nodeEvents:
            enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: argo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  syncOptions:
    - CreateNamespace=true

  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /status
        - /metadata/annotations
        - /metadata/managedFields

# =====================================================================================
# STORAGECLASS
# =====================================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ids-storageclass
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: values/storageclass
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /status
        - /metadata/annotations
        - /metadata/managedFields

---
# =====================================================================================
# IDS RETRAIN WORKFLOWS (CronWorkflow)
# =====================================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ids-retrain
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: values/argo-workflows     
  destination:
    server: https://kubernetes.default.svc
    namespace: argo                 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
    - group: argoproj.io
      kind: CronWorkflow
      jsonPointers:
        - /status
        - /metadata/annotations
        - /metadata/managedFields
